/* Selecionando Dados da Tabela Aluno */
SELECT
	NOME				AS [NOME COMPLETO]
  , MATRICULA			AS [MAT]
  , DATANASCIMENTO		AS [NASCIMENTO]
  , SEXO
FROM
	[SQL_DE_CADA_DIA].[DBO].[ALUNO]
GO


SELECT
	MATRICULA			AS [MAT]
  , COD_TURMA			AS [CODIGO DA TURMA]
  , NOTA				AS [NOTA ANTERIOR]
  , NOTA + 0.5			AS [NOTA COM ACRESCIMO]
FROM
	[SQL_DE_CADA_DIA].[DBO].[FREQUENTA]
GO