/* Selecionando Dados da Tabela */
SELECT
    MAX(NOTA)			AS [NOTA MÁXIMA]
  , MIN(NOTA)			AS [NOTA MÍNIMA]
  , AVG(NOTA)			AS [MÉDIA DAS NOTAS]
  , SUM(NOTA)			AS [SOMA DAS NOTAS]
  , COUNT(*)			AS [CONTAGEM DAS LINHAS]
FROM
	[SQL_DE_CADA_DIA].[DBO].[FREQUENTA]
GO


SELECT
    COD_TURMA
  , SEMESTRE
  , AVG(NOTA)			AS [NOTA MÉDIA]
FROM
	[SQL_DE_CADA_DIA].[DBO].[FREQUENTA]
GROUP BY
    COD_TURMA
  , SEMESTRE
GO


SELECT
    COD_TURMA
  , SEMESTRE
  , AVG(NOTA)			AS [NOTA MÉDIA]
  , MAX(NOTA)			AS [NOTA MÁXIMA]
FROM
	[SQL_DE_CADA_DIA].[DBO].[FREQUENTA]
GROUP BY
    COD_TURMA
  , SEMESTRE
GO
