/* Criando um Banco de Dados */
CREATE DATABASE
	SQL_DE_CADA_DIA
GO


/* Escolhendo um Banco de Dados */
USE
	SQL_DE_CADA_DIA
GO


/* Criando a Tabela Aluno */
CREATE TABLE ALUNO (
    MATRICULA VARCHAR(20) NOT NULL
  , NOME VARCHAR(100)
  , SEXO CHAR(1),
    CPF VARCHAR(11)
  , RG VARCHAR(10)
  , DATANASCIMENTO DATE
  , CIDADE VARCHAR(50)
  , BAIRRO VARCHAR(50)
  , CEP VARCHAR(10)
  , ENDERECO VARCHAR(50)
  , CONSTRAINT "PK_ALUNO" PRIMARY KEY (MATRICULA)
)


/* Criando a Tabela Professor */
CREATE TABLE PROFESSOR(
    MATRICULA VARCHAR(20) NOT NULL
  , NOME VARCHAR(100)
  , SEXO CHAR(1)
  , CPF VARCHAR(11)
  , RG VARCHAR(10)
  , DATANASCIMENTO DATE
  , ESPECIALIDADE VARCHAR(100)
  , DATAFORMACAO DATE
  , NOME_FACULDA_DE_FORMACAO VARCHAR(100)
  , CIDADE VARCHAR(50)
  , BAIRRO VARCHAR(50)
  , CEP VARCHAR(10)
  , ENDERECO VARCHAR(50)
  , CONSTRAINT "PK_PROFESSOR" PRIMARY KEY (MATRICULA)
)


/* Criando Tabela Disciplina */
CREATE TABLE DISCIPLINA(
    COD_DISCIPLINA VARCHAR(20) NOT NULL 
  , NOME_DISCIPLINA VARCHAR(100)
  , CARGA_HORARIA INT
  , CONSTRAINT "PK_DISCIPLINA" PRIMARY KEY (COD_DISCIPLINA)
)


/* Criando Tabela Turma */
CREATE TABLE TURMA(
    COD_TURMA VARCHAR(20) NOT NULL
  , COD_DISCIPLINA VARCHAR(20) NOT NULL
  , NOME_TURMA VARCHAR(100)
  , SALA VARCHAR(10)
  , TURNO VARCHAR(20)
  , CONSTRAINT "PK_TURMA" PRIMARY KEY (COD_TURMA)
  , CONSTRAINT "FK_TURMA" FOREIGN KEY (COD_DISCIPLINA) REFERENCES DISCIPLINA (COD_DISCIPLINA) 
)


/* Criando Tabela Frequenta */
CREATE TABLE FREQUENTA(
    MATRICULA VARCHAR(20) NOT NULL
  , COD_TURMA VARCHAR(20) NOT NULL
  , NOTA NUMERIC(4,2)
  , FALTA INT
  , SEMESTRE INT
  , ANO INT
  , CONSTRAINT "FK_FREQUENTA_MATRICULA" FOREIGN KEY (MATRICULA) REFERENCES ALUNO (MATRICULA)
  , CONSTRAINT "FK_FREQUENTA_CODTURMA" FOREIGN KEY (COD_TURMA) REFERENCES TURMA (COD_TURMA) 
)


/* Criando Tabela Ensina */
CREATE TABLE ENSINA(
    MATRICULA VARCHAR(20) NOT NULL
  , COD_TURMA VARCHAR(20) NOT NULL
  , CONSTRAINT "FK_ENSINA_MATRICULA" FOREIGN KEY (MATRICULA) REFERENCES PROFESSOR (MATRICULA)
  , CONSTRAINT "FK_ENSINA_CODTURMA" FOREIGN KEY (COD_TURMA) REFERENCES TURMA (COD_TURMA) 
)
GO
