/* Selecionando Dados das Tabelas */
SELECT
	A.MATRICULA
  , A.NOME
  , F.COD_TURMA
FROM
	[SQL_DE_CADA_DIA].[DBO].[ALUNO] A
  , [SQL_DE_CADA_DIA].[DBO].[FREQUENTA] F
WHERE
	A.MATRICULA = F.MATRICULA
GO


SELECT
	A.MATRICULA
  , A.NOME
  , F.COD_TURMA
FROM
	[SQL_DE_CADA_DIA].[DBO].[ALUNO] A
INNER JOIN [SQL_DE_CADA_DIA].[DBO].[FREQUENTA] F ON A.MATRICULA = F.MATRICULA
GO


SELECT
	A.MATRICULA
  , A.NOME
  , F.COD_TURMA
FROM
	[SQL_DE_CADA_DIA].[DBO].[ALUNO] A
JOIN [SQL_DE_CADA_DIA].[DBO].[FREQUENTA] F ON A.MATRICULA = F.MATRICULA
GO


/* Inserindo Dados na Tabela Aluno */
INSERT INTO 
	[SQL_DE_CADA_DIA].[DBO].[ALUNO]
VALUES(
	'UC12456711'
  , 'Ana Valente'
  , 'F'
  , NULL
  , NULL
  , NULL
  , NULL
  , NULL
  , NULL
  , NULL
)
GO


/* Selecionando Dados das Tabelas */
SELECT
	A.MATRICULA
  , A.NOME
  , F.COD_TURMA
FROM
	[SQL_DE_CADA_DIA].[DBO].[ALUNO] A
LEFT JOIN [SQL_DE_CADA_DIA].[DBO].[FREQUENTA] F ON A.MATRICULA = F.MATRICULA
GO


SELECT
	A.MATRICULA
  , A.NOME
  , F.COD_TURMA
FROM
	[SQL_DE_CADA_DIA].[DBO].[ALUNO] A
RIGHT JOIN [SQL_DE_CADA_DIA].[DBO].[FREQUENTA] F ON A.MATRICULA = F.MATRICULA
GO

SELECT
	A.MATRICULA
  , A.NOME
  , F.COD_TURMA
FROM
	[SQL_DE_CADA_DIA].[DBO].[ALUNO] A
CROSS JOIN [SQL_DE_CADA_DIA].[DBO].[FREQUENTA] F
GO