/* Selecionando Dados da Tabela */
SELECT
	NOME
  , DATANASCIMENTO
FROM
	[SQL_DE_CADA_DIA].[DBO].[ALUNO]
WHERE
	CONVERT(VARCHAR, DATANASCIMENTO) = '1990-06-25'
GO


SELECT
	AVG(NOTA)			AS [NOTA]
FROM
	[SQL_DE_CADA_DIA].[DBO].[FREQUENTA]
GO