/* Criando Tabelas */
CREATE TABLE [SQL_DE_CADA_DIA].[DBO].[AVALIACAOMEC](
	ID_AVALIACAO VARCHAR(5) PRIMARY KEY
	, CPF_PRIMEIRO_AUDITOR VARCHAR(11)
	, CPF_SEGUNDO_AUDITOR VARCHAR(11)
	, CPF_TERCEIRO_AUDITOR VARCHAR(11)
	, NOTA_FINAL INT
)
GO


/* Selecionando Dados da Tabela */
SELECT
	*
FROM
	[SQL_DE_CADA_DIA].[DBO].[AVALIACAOMEC]
GO


/* Inserindo Dados na Tabela */
INSERT INTO
	[SQL_DE_CADA_DIA].[DBO].[AVALIACAOMEC]
VALUES(
	'4512A'
  , '02247752102'
  , '03247765120'
  , '05831145123'
  , 4
)
GO


/* Apagando uma Tabela */
DROP TABLE
	[SQL_DE_CADA_DIA].[DBO].[AVALIACAOMEC]
GO